language: node_js
node_js:
  - node

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "cdn.tcff.co"
  skip_cleanup: true
  acl: public_read 
